spring:
  datasource:
    url: jdbc:h2:mem:cafeerpdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console   # http://localhost:8080/h2-console ?? ??

  jpa:
    hibernate:
      ddl-auto: update    # ?? ??: create, update / ??: validate, none ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

jwt:
  private-key-path: ""   # ?? ????? ???? ?
  public-key-path: ""    # ?? ????? ?? ??
  expiration: 3600000

